# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tutorNtutee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tutorNtutee
	pod 'Firebase/Auth'
        pod 'Firebase/Analytics'
        pod 'Firebase/Database'
        pod 'Firebase/Firestore'
	pod 'Firebase/Storage'
end
